#define SCRIPT_REALNAME "gl_g_sneak_spotted"
#include "../source/headers/fo2tweaks/fo2tweaks.h"

#define set_sneak_spotted "sneak_spotted"
#define sec_sneak_spotted "sneak_spotted"
#define set_sneak_spotted_msg "message"
#define set_sneak_spotted_stop "stop"

procedure start;

procedure start begin
  variable stop;
  variable spotted_msg;
    stop = fo2tweaks_setting(set_sneak_spotted, set_sneak_spotted_stop);
    spotted_msg = fo2tweaks_string(set_sneak_spotted, set_sneak_spotted_msg);
  if game_loaded then begin
    variable enabled = fo2tweaks_setting(sec_main, set_sneak_spotted);
    if enabled == 1 then begin
      set_global_script_repeat(60);
      ndebug("initialized");
    end
  end else begin
    if dude_is_sneaking and not sneak_success then begin
      ndebug("spotted player");
      display_msg(spotted_msg);
      if stop then begin
        reg_anim_clear(dude_obj);
      end
    end
  end
end
