#define SCRIPT_REALNAME "gl_g_custom_ai"
#include "headers/fo2tweaks/fo2tweaks.h"


//variable enabled;

procedure start;

procedure start begin

  if game_loaded then begin
    variable fs_override = check_filesystem_override;
//    enabled = fo2tweaks_setting(sec_main, set_run_speed);
    variable enabled = true;
    if enabled and fs_override then begin
      variable old_party = "data\\party.txt";
      variable new_party = "data\\custom_party.txt";
      variable file = fs_copy(new_party, old_party);
      ndebug("file is " + file);
      ndebug("initialized");
    end
  end
end
