{1}{}{Les handicaps sont guéris.}
{2}{}{N'a pas réussi à guérir les handicaps.}
{3}{}{Tu ne peux pas faire durant un combat.}
{4}{}{Tu penses qu'il n'y a aucune chance que tu puisses guérir ça.}
{5}{}{ est déjà en bonne santé.}
{6}{}{%1% a déjà été soigné avec la compétence %2% aujourd'hui. Essaye demain.}
{7}{}{Tu ne parviens pas à guérir.}
{8}{}{Wouah, maintenant je sais vraiment comment leur faire mal !}
{9}{}{a gagné la compétence Anatomie vivante.}
{10}{}{Tu reçoit %1% points d'expérience pour l'utilisation réussie de ta compétence %2%.}
{11}{}{%1% a récupéré %2% PI.}
{12}{}{Dead. Too late to help this one. }
