language: shell
os: linux
dist: focal

cache:
  directories:
    - $HOME/.cache/build

addons:
  apt:
    update: true
    packages:
      - moreutils
      - nsis
      - p7zip
      - wine-stable
      - wine32

before_install:
  - ./extra/prepare.sh

script:
  - ./extra/buildall.sh
  - ./extra/build_nsis.sh
  - ./extra/publish.sh

env:
  global:
    - sfall_version: 4.2.8.1
    - mpack_version: 4.2.8.1
    - mods_dir: mods
    - mod_name: fo2tweaks
    - bin_dir: extra/bin

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file_glob: true
  file: fo2tweaks*.zip
  cleanup: false
  on:
    tags: true
    branch: master
