import tseslint from 'typescript-eslint';
import tsParser from "@typescript-eslint/parser";
import unusedImports from 'eslint-plugin-unused-imports';

// Engine entry points and special variables - not directly referenced but called by engine
const IGNORE_UNUSED = [
    // Engine procedures
    'barter_init_p_proc',
    'barter_p_proc',
    'combat_p_proc',
    'create_p_proc',
    'critter_p_proc',
    'damage_p_proc',
    'description_p_proc',
    'destroy_p_proc',
    'drop_p_proc',
    'look_at_p_proc',
    'map_enter_p_proc',
    'map_exit_p_proc',
    'map_update_p_proc',
    'pickup_p_proc',
    'spatial_p_proc',
    'start',
    'talk_p_proc',
    'timed_event_p_proc',
    'use_ad_on_p_proc',
    'use_disad_on_p_proc',
    'use_obj_on_p_proc',
    'use_p_proc',
    'use_skill_on_p_proc',
    // Special variables
    'SCRIPT_NAME',
    'SCRIPT_REALNAME',
];

// SSL reserved words - engine globals and builtins that should not be shadowed (from folib/base.d.ts)
const SSL_RESERVED_WORDS = [
  "action_being_used",
  "add_mult_objs_to_inven",
  "AddNamedEvent",
  "AddNamedHandler",
  "add_obj_to_inven",
  "add_timer_event",
  "anim",
  "anim_action_frame",
  "anim_busy",
  "animate_move_obj_to_tile",
  "animate_rotation",
  "animate_run_to_tile",
  "animate_set_frame",
  "animate_stand",
  "animate_stand_obj",
  "animate_stand_reverse",
  "animate_stand_reverse_obj",
  "art_anim",
  "attack_complex",
  "attack_setup",
  "ClearNamed",
  "combat_difficulty",
  "combat_is_initialized",
  "create_object_sid",
  "critter_add_trait",
  "critter_attempt_placement",
  "critter_dmg",
  "critter_heal",
  "critter_injure",
  "critter_inven_obj",
  "critter_is_fleeing",
  "critter_mod_skill",
  "critter_rm_trait",
  "critter_set_flee_state",
  "critter_state",
  "critter_stop_attacking",
  "cur_map_index",
  "days_since_visited",
  "debug_msg",
  "destroy_mult_objs",
  "destroy_object",
  "dialogue_reaction",
  "dialogue_system_enter",
  "difficulty_level",
  "display_msg",
  "do_check",
  "drop_obj",
  "dude_obj",
  "elevation",
  "end_dialogue",
  "endgame_movie",
  "endgame_slideshow",
  "explosion",
  "fixed_param",
  "float_msg",
  "floor",
  "format",
  "game_ticks",
  "game_time",
  "game_time_advance",
  "game_time_hour",
  "game_ui_disable",
  "game_ui_enable",
  "game_ui_is_disabled",
  "gdialog_mod_barter",
  "gdialog_set_barter_mod",
  "get_critter_stat",
  "get_day",
  "get_month",
  "get_pc_stat",
  "get_poison",
  "gfade_in",
  "gfade_out",
  "giQ_Option",
  "give_exp_points",
  "global_var",
  "gSay_End",
  "gSay_Message",
  "gSay_Option",
  "gSay_Reply",
  "gSay_Start",
  "has_skill",
  "has_trait",
  "how_much",
  "inven_cmds",
  "is_critical",
  "is_success",
  "item_caps_adjust",
  "item_caps_total",
  "jam_lock",
  "kill_critter",
  "kill_critter_type",
  "load_map",
  "local_var",
  "map_var",
  "message_str",
  "metarule",
  "metarule3",
  "move_obj_inven_to_obj",
  "move_to",
  "obj_art_fid",
  "obj_being_used_with",
  "obj_can_hear_obj",
  "obj_can_see_obj",
  "obj_carrying_pid_obj",
  "obj_close",
  "obj_is_carrying_obj_pid",
  "obj_is_locked",
  "obj_is_open",
  "obj_item_subtype",
  "obj_lock",
  "obj_name",
  "obj_on_screen",
  "obj_open",
  "obj_pid",
  "obj_set_light_level",
  "obj_type",
  "obj_unlock",
  "override_map_start",
  "party_add",
  "party_member_obj",
  "party_remove",
  "pickup_obj",
  "play_gmovie",
  "play_sfx",
  "poison",
  "proto_data",
  "radiation_dec",
  "radiation_inc",
  "random",
  "reg_anim_animate",
  "reg_anim_animate_forever",
  "reg_anim_animate_reverse",
  "reg_anim_end",
  "reg_anim_func",
  "reg_anim_obj_move_to_obj",
  "reg_anim_obj_move_to_tile",
  "reg_anim_obj_run_to_obj",
  "reg_anim_obj_run_to_tile",
  "reg_anim_play_sfx",
  "rm_mult_objs_from_inven",
  "rm_obj_from_inven",
  "rm_timer_event",
  "roll_vs_skill",
  "rotation_to_tile",
  "running_burning_guy",
  "script_action",
  "script_overrides",
  "scr_return",
  "self_obj",
  "set_critter_stat",
  "set_exit_grids",
  "set_global_var",
  "set_light_level",
  "set_local_var",
  "set_map_music",
  "set_map_start",
  "set_map_var",
  "set_obj_visibility",
  "SignalNamed",
  "skill_contest",
  "source_obj",
  "start_gdialog",
  "target_obj",
  "terminate_combat",
  "tile_contains_obj_pid",
  "tile_contains_pid_obj",
  "tile_distance",
  "tile_distance_objs",
  "tile_is_visible",
  "tile_num",
  "tile_num_in_direction",
  "tokenize",
  "town_map",
  "use_obj",
  "use_obj_on_obj",
  "using_skill",
  "wield_obj_critter",
  "wm_area_set_pos",
  "world_map",
];

// Sfall reserved words (from folib/sfall/sfall.d.ts)
const SFALL_RESERVED_WORDS = [
  "abs",
  "activate_shader",
  "active_hand",
  "add_g_timer_event",
  "apply_heaveho_fix",
  "arctan",
  "array_key",
  "arrayexpr",
  "art_exists",
  "atof",
  "atoi",
  "available_global_script_types",
  "block_combat",
  "call_offset_r0",
  "call_offset_r1",
  "call_offset_r2",
  "call_offset_r3",
  "call_offset_r4",
  "call_offset_v0",
  "call_offset_v1",
  "call_offset_v2",
  "call_offset_v3",
  "call_offset_v4",
  "ceil",
  "charcode",
  "clear_selectable_perks",
  "cos",
  "create_array",
  "create_message_window",
  "create_spatial",
  "deactivate_shader",
  "disable_aimed_shots",
  "div",
  "eax_available",
  "exponent",
  "fix_array",
  "force_aimed_shots",
  "force_encounter",
  "force_encounter_with_flags",
  "force_graphics_refresh",
  "free_array",
  "free_shader",
  "fs_copy",
  "fs_create",
  "fs_delete",
  "fs_find",
  "fs_pos",
  "fs_read_byte",
  "fs_read_float",
  "fs_read_int",
  "fs_read_short",
  "fs_resize",
  "fs_seek",
  "fs_size",
  "fs_write_bstring",
  "fs_write_byte",
  "fs_write_float",
  "fs_write_int",
  "fs_write_short",
  "fs_write_string",
  "game_loaded",
  "gdialog_get_barter_mod",
  "get_array",
  "get_attack_type",
  "get_available_skill_points",
  "get_bodypart_hit_modifier",
  "get_critical_table",
  "get_critter_base_stat",
  "get_critter_current_ap",
  "get_critter_extra_stat",
  "get_critter_skill_points",
  "get_game_mode",
  "get_ini_setting",
  "get_ini_string",
  "get_inven_ap_cost",
  "get_kill_counter",
  "get_last_attacker",
  "get_last_target",
  "get_light_level",
  "get_map_enter_position",
  "get_metarule_table",
  "get_mouse_buttons",
  "get_mouse_x",
  "get_mouse_y",
  "get_npc_level",
  "get_pc_base_stat",
  "get_pc_extra_stat",
  "get_perk_available",
  "get_perk_owed",
  "get_proto_data",
  "get_screen_height",
  "get_screen_width",
  "get_script",
  "get_sfall_arg",
  "get_sfall_args",
  "get_sfall_global_float",
  "get_sfall_global_int",
  "get_shader_texture",
  "get_shader_version",
  "get_stat_max",
  "get_stat_min",
  "get_string_pointer",
  "get_tile_fid",
  "get_unspent_ap_bonus",
  "get_unspent_ap_perk_bonus",
  "get_uptime",
  "get_viewport_x",
  "get_viewport_y",
  "get_weapon_ammo_count",
  "get_weapon_ammo_pid",
  "get_window_attribute",
  "get_window_under_mouse",
  "get_world_map_x_pos",
  "get_world_map_y_pos",
  "get_year",
  "graphics_funcs_available",
  "has_fake_perk",
  "has_fake_trait",
  "hero_select_win",
  "hide_iface_tag",
  "hide_real_perks",
  "in_world_map",
  "inc_npc_level",
  "init_hook",
  "input_funcs_available",
  "interface_overlay",
  "is_iface_tag_active",
  "key_pressed",
  "len_array",
  "list",
  "list_as_array",
  "list_begin",
  "list_end",
  "list_next",
  "load_array",
  "load_shader",
  "log",
  "map",
  "mark_movie_played",
  "message_box",
  "message_str_game",
  "metarule2_explosions",
  "metarule3",
  "mod_kill_counter",
  "mod_skill_points_per_level",
  "modified_ini",
  "nb_create_char",
  "obj_blocking_line",
  "obj_blocking_tile",
  "obj_is_carrying_obj",
  "party_member_list",
  "path_find_to",
  "perk_add_mode",
  "play_sfall_sound",
  "read_byte",
  "read_int",
  "read_short",
  "read_string",
  "refresh_pc_art",
  "reg_anim_animate_and_hide",
  "reg_anim_callback",
  "reg_anim_change_fid",
  "reg_anim_combat_check",
  "reg_anim_destroy",
  "reg_anim_light",
  "reg_anim_take_out",
  "reg_anim_turn_towards",
  "register_hook",
  "register_hook_proc",
  "register_hook_proc_spec",
  "remove_attacker_knockback",
  "remove_script",
  "remove_target_knockback",
  "remove_trait",
  "remove_weapon_knockback",
  "reset_critical_table",
  "resize_array",
  "resume_game",
  "round",
  "save_array",
  "scan_array",
  "seq_perk_freq",
  "set_array",
  "set_attacker_knockback",
  "set_available_skill_points",
  "set_base_hit_chance_mod",
  "set_base_pickpocket_mod",
  "set_base_skill_mod",
  "set_bodypart_hit_modifier",
  "set_car_current_town",
  "set_critical_table",
  "set_critter_base_stat",
  "set_critter_burst_disable",
  "set_critter_current_ap",
  "set_critter_extra_stat",
  "set_critter_hit_chance_mod",
  "set_critter_pickpocket_mod",
  "set_critter_skill_mod",
  "set_critter_skill_points",
  "set_df_model",
  "set_dm_model",
  "set_eax_environment",
  "set_fake_perk",
  "set_fake_trait",
  "set_global_script_repeat",
  "set_global_script_type",
  "set_hero_race",
  "set_hero_style",
  "set_hit_chance_max",
  "set_hp_per_level_mod",
  "set_inven_ap_cost",
  "set_map_time_multi",
  "set_movie_path",
  "set_npc_stat_max",
  "set_npc_stat_min",
  "set_palette",
  "set_pc_base_stat",
  "set_pc_extra_stat",
  "set_pc_stat_max",
  "set_pc_stat_min",
  "set_perk_agl",
  "set_perk_chr",
  "set_perk_desc",
  "set_perk_end",
  "set_perk_freq",
  "set_perk_image",
  "set_perk_int",
  "set_perk_lck",
  "set_perk_level",
  "set_perk_level_mod",
  "set_perk_name",
  "set_perk_owed",
  "set_perk_per",
  "set_perk_ranks",
  "set_perk_skill1",
  "set_perk_skill1_mag",
  "set_perk_skill2",
  "set_perk_skill2_mag",
  "set_perk_stat",
  "set_perk_stat_mag",
  "set_perk_str",
  "set_perk_type",
  "set_perkbox_title",
  "set_pickpocket_max",
  "set_pipboy_available",
  "set_proto_data",
  "set_pyromaniac_mod",
  "set_script",
  "set_selectable_perk",
  "set_self",
  "set_sfall_arg",
  "set_sfall_global",
  "set_sfall_return",
  "set_shader_float",
  "set_shader_int",
  "set_shader_mode",
  "set_shader_texture",
  "set_shader_vector",
  "set_skill_max",
  "set_stat_max",
  "set_stat_min",
  "set_swiftlearner_mod",
  "set_target_knockback",
  "set_unspent_ap_bonus",
  "set_unspent_ap_perk_bonus",
  "set_viewport_x",
  "set_viewport_y",
  "set_weapon_ammo_count",
  "set_weapon_ammo_pid",
  "set_weapon_knockback",
  "set_world_map_pos",
  "set_xp_mod",
  "sfall_func0",
  "sfall_func1",
  "sfall_func2",
  "sfall_func3",
  "sfall_func4",
  "sfall_func5",
  "sfall_func6",
  "sfall_func7",
  "sfall_func8",
  "sfall_typeof",
  "sfall_ver_build",
  "sfall_ver_major",
  "sfall_ver_minor",
  "show_iface_tag",
  "show_real_perks",
  "sin",
  "sneak_success",
  "sprintf",
  "sqrt",
  "stop_game",
  "stop_sfall_sound",
  "string_format",
  "string_format_array",
  "string_replace",
  "string_split",
  "string_to_case",
  "strlen",
  "substr",
  "tan",
  "tap_key",
  "temp_array",
  "tile_get_objs",
  "tile_light",
  "tile_under_cursor",
  "toggle_active_hand",
  "write_byte",
  "write_int",
  "write_short",
  "write_string",
];

// TypeScript syntax that breaks transpilation or produces broken SSL
const TSSL_FORBIDDEN_SYNTAX = [
  ["ArrowFunctionExpression", "Arrow functions are not supported. Use regular function declarations."],
  ["TemplateLiteral", "Template literals are not supported. Use string concatenation with +."],
  ["ChainExpression", "Optional chaining (?.) is not supported in SSL."],
  ["LogicalExpression[operator='??']", "Nullish coalescing (??) is not supported. Use explicit null/0 checks."],
  ["SpreadElement", "Spread operator (...) is not supported in SSL."],
  ["BinaryExpression[operator='**']", "Exponentiation (**) is not supported. Use power() or manual multiplication."],
  ["Property[shorthand=true]", "Shorthand properties ({x}) are not supported. Use explicit {x: x}."],
  ["ArrayPattern:not(ForOfStatement ArrayPattern)", "Array destructuring is not supported. Access elements by index. (for-of [k,v] is OK)"],
  ["ObjectPattern", "Object destructuring is not supported. Access properties explicitly."],
  ["UnaryExpression[operator='typeof']", "typeof is not supported. Use typeof_() sfall function."],
  ["BinaryExpression[operator='instanceof']", "instanceof is not supported in SSL."],
  ["NewExpression", "new keyword is not supported. SSL has no constructors."],
  ["AwaitExpression", "await is not supported. SSL is synchronous."],
  ["YieldExpression", "yield is not supported. SSL has no generators."],
  ["AssignmentExpression[operator='??=']", "Nullish assignment (??=) is not supported."],
  ["AssignmentExpression[operator='||=']", "Logical OR assignment (||=) is not supported."],
  ["AssignmentExpression[operator='&&=']", "Logical AND assignment (&&=) is not supported."],
  ["BinaryExpression[operator='in']", "'in' operator is not supported. Use is_in_array() or scan_array()."],
  ["ClassDeclaration", "Classes are not supported in SSL."],
  ["ClassExpression", "Classes are not supported in SSL."],
  ["TaggedTemplateExpression", "Tagged templates are not supported in SSL."],
];

// JS globals not available in SSL runtime
const JS_UNAVAILABLE_GLOBALS = [
  ["Array", "Array constructor is not available in SSL runtime. Use sfall temp_array or create_array."],
  ["Date", "Date is not available in SSL runtime."],
  ["JSON", "JSON is not available in SSL runtime."],
  ["Map", "Map is not available in SSL runtime. Use sfall temp_array_map."],
  ["Math", "Math is not available in SSL runtime. Use sfall functions (floor2, ceil2, abs2, etc)."],
  ["Object", "Object is not available in SSL runtime. Use sfall arrays and scan_array for iteration."],
  ["Promise", "Promise is not available in SSL runtime."],
  ["Proxy", "Proxy is not available in SSL runtime."],
  ["Reflect", "Reflect is not available in SSL runtime."],
  ["Set", "Set is not available in SSL runtime."],
];

export default tseslint.config(
  ...tseslint.configs.recommendedTypeChecked.map(config => ({
    ...config,
    files: ["**/*.ts", "**/*.tssl"],
  })),
  {
    files: ["**/*.ts", "**/*.tssl"],
    languageOptions: {
      ecmaVersion: 2020,
      sourceType: "module",
      parser: tsParser,
      parserOptions: {
        projectService: true,
        extraFileExtensions: ['.tssl'],
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: {
      'unused-imports': unusedImports,
    },
    rules: {
      'unused-imports/no-unused-imports': 'error',
      '@typescript-eslint/no-unused-vars': ['warn', {
        varsIgnorePattern: `^(${IGNORE_UNUSED.join('|')}|_)`,
        argsIgnorePattern: '^_',
      }],
      '@typescript-eslint/no-explicit-any': 'off',
      "no-restricted-globals": [
        "error",
        ...JS_UNAVAILABLE_GLOBALS.map(([name, message]) => ({ name, message })),
      ],
      "no-restricted-syntax": [
        "error",
        ...[...new Set([...SSL_RESERVED_WORDS, ...SFALL_RESERVED_WORDS])].map(name => ({
          selector: `:matches(VariableDeclarator[id.name='${name}'], FunctionDeclaration[id.name='${name}'], Property[key.name='${name}'])`,
          message: `'${name}' is a reserved word in SSL and cannot be used as a variable/function/parameter name.`,
        })),
        ...TSSL_FORBIDDEN_SYNTAX.map(([selector, message]) => ({ selector, message })),
      ],
    },
  },
  {
    ignores: ['node_modules/**', '**/*.mjs', 'source/*.ts'],
  }
);
