{1}{}{Niepełnosprawności wyleczone.}
{2}{}{Nie udało się wyleczyć niepełnosprawności.}
{3}{}{Nie możesz tego zrobić w trybie walki.}
{4}{}{Nie sądzisz, że jesteś w stanie to wyleczyć.}
{5}{}{ jest już wyleczony.}
{6}{}{%1% zostało już dzisiaj wylecznone za pomocą umiejętności %2%. Spróbuj jutro.}
{7}{}{Nie udaje się ci wyleczyć.}
{8}{}{Wow, teraz naprawdę wiem, jak ich ranić!}
{9}{}{zdobył profit Żywa Anatomia.}
{10}{}{Otrzymujesz %1% doświadczenia za udane użycie umiejętności %2%.}
{11}{}{%1% wyleczył %2% HP.}
{12}{}{Nie żyje. Jest za późno żeby pomóc.}
