{1}{}{Niepe?nosprawno?ci wyleczone.}
{2}{}{Nie uda?o si? wyleczy? niepe?nosprawno?ci.}
{3}{}{Nie mo?esz tego zrobi? w trybie walki.}
{4}{}{Nie s?dzisz, ?e jeste? w stanie to wyleczy?.}
{5}{}{ jest ju? wyleczony.}
{6}{}{%1% zosta?o ju? dzisiaj wylecznone za pomoc? umiej?tno?ci %2%. Spróbuj jutro.}
{7}{}{Nie udaje si? ci wyleczy?.}
{8}{}{Wow, teraz naprawd? wiem, jak ich rani?!}
{9}{}{zdoby? profit ?ywa Anatomia.}
{10}{}{Otrzymujesz %1% do?wiadczenia za udane u?ycie umiej?tno?ci %2%.}
{11}{}{%1% wyleczy? %2% HP.}
{12}{}{Dead. Too late to help this one. }
