{1}{}{Niepe³nosprawnoœci wyleczone.}
{2}{}{Nie uda³o siê wyleczyæ niepe³nosprawnoœci.}
{3}{}{Nie mo¿esz tego zrobiæ w trybie walki.}
{4}{}{Nie s¹dzisz, ¿e jesteœ w stanie to wyleczyæ.}
{5}{}{ jest ju¿ wyleczony.}
{6}{}{%1% zosta³o ju¿ dzisiaj wylecznone za pomoc¹ umiejêtnoœci %2%. Spróbuj jutro.}
{7}{}{Nie udaje siê ci wyleczyæ.}
{8}{}{Wow, teraz naprawdê wiem, jak ich raniæ!}
{9}{}{zdoby³ profit ¯ywa Anatomia.}
{10}{}{Otrzymujesz %1% doœwiadczenia za udane u¿ycie umiejêtnoœci %2%.}
{11}{}{%1% wyleczy³ %2% HP.}
{12}{}{Nie ¿yje. Jest za póŸno ¿eby pomóc.}
