{1}{}{Discapacidad sanado.}
{2}{}{No pudo sanar discapasidad.}
{3}{}{No puedes hacer eso en combate.}
{4}{}{No crees que haya alguna possibilidad que puedes curar esto.}
{5}{}{Esta criatura ya está sana.}
{6}{}{Ya has usado esta habilidad en esta criatura hoy.}
{7}{}{No consigues curar nada.}
{8}{}{¡Caray! ¡Ahora realmente se cómo herir a alguien!}
{9}{}{ha ganado Anatomía vital.}
{10}{}{Ganas %1% puntos de experiencia por el uso de %2%.}
{11}{}{%1% curado para %2% PS.}
