{1}{}{Discapacidades curadas.}
{2}{}{No se pudieron curar las discapacidades.}
{3}{}{No puedes hacer esto en combate.}
{4}{}{No crees que haya alguna posibilidad de curar esto.}
{5}{}{ ya está sano.}
{6}{}{%1% ya ha sido curado con la habilidad de %2% hoy. Inténtalo mañana.}
{7}{}{No consigues curar nada.}
{8}{}{¡Vaya! ¡Ahora realmente sé cómo herir a alguien!}
{9}{}{ha ganado la habilidad Anatomía Viviente.}
{10}{}{Ganas %1% puntos de experiencia por el uso de %2%.}
{11}{}{%1% curado para %2% PS.}
{12}{}{Muerto. Demasiado tarde para ayudarlo.}
