{1}{}{Discapacidades curadas.}
{2}{}{No pudo curar las discapacidades.}
{3}{}{No puedes hacer eso en combate.}
{4}{}{No crees que haya ninguna posibilidad de que puedas curar esto.}
{5}{}{ is already healthy.}
{6}{}{%1% has already been healed with %2% skill today. Try tomorrow.}
{7}{}{No consigues curar nada.}
{8}{}{¡Wow! ¡Ahora realmente sé cómo herir a alguien!}
{9}{}{ha ganado Anatomía Vital.}
{10}{}{Ganas %1% puntos de experiencia por el uso de %2%.}
{11}{}{%1% curado para %2% PS.}
{12}{}{Muerto. Demasiado tarde para ayudarlo.}
