{1}{}{Deficiências curadas.}
{2}{}{Falhou em curar as deficiências.}
{3}{}{Você não pode fazer isto no combate.}
{4}{}{Você não acha que há qualquer chance de que você consiga curar isto.}
{5}{}{ is already healthy.}
{6}{}{%1% has already been healed with %2% skill today. Try tomorrow.}
{7}{}{Você falha em fazer qualquer cura.}
{8}{}{Uau, agora eu realmente sei como ferir eles!}
{9}{}{ganhou o bônus da Anatomia Viva.}
{10}{}{Você recebe %1% de experiência pelo uso bem-sucedido da técnica %2%.}
{11}{}{O %1% curou %2% de HP.}
{12}{}{Morto. Tarde demais pra ajudar este.}
