{1}{}{Deficiências curadas.}
{2}{}{Falhou em curar as deficiências.}
{3}{}{Você não pode fazer isto em combate.}
{4}{}{Você não acha que há qualquer chance de que você conseguiria curar isto.}
{5}{}{ já está saudável.}
{6}{}{O %1% já foi curado com a técnica %2% hoje. Tente amanhã.}
{7}{}{Você falha em fazer qualquer cura.}
{8}{}{Uau, agora eu realmente sei como ferir eles!}
{9}{}{ganhou o bônus da Anatomia Viva.}
{10}{}{Você recebe %1% de experiência pelo uso bem-sucedido da técnica %2%.}
{11}{}{O %1% curou %2% de HP.}
{12}{}{Morto. Tarde demais pra ajudar esta pessoa.}
