{1}{}{Handikapp läkte.}
{2}{}{Misslyckades att läka handikapp.}
{3}{}{Du kan inte göra detta i strid.}
{4}{}{Du tror inte att det finns någon chans att du skulle kunna läka detta.}
{5}{}{ är redan hälsosam.}
{6}{}{%1% har redan blivit läkt med %2% fädigheten idag. Försök igen imorgon.}
{7}{}{Du misslyckas att hela.}
{8}{}{Wow, nu vet jag verkligen hur jag kan skada dem!}
{9}{}{has uppnått Levande Anatomi-förmånen.}
{10}{}{Du får %1% erfarenhet för att du lyckas använda din %2% färdighet.}
{11}{}{%1% läkte %2% HP.}
{12}{}{Död. För sent för att hjälpa den här.}
