{1}{}{Disabilita' curate.}
{2}{}{Cura fallita delle disabilita'.}
{3}{}{Non puoi farlo in combattimento.}
{4}{}{Non pensi che ci sia alcuna possibilita' di curarti.}
{5}{}{ e' gia' in salute.}
{6}{}{%1% e' stato gia' curato con l'abilita' %2% oggi. Riprova domani.}
{7}{}{Hai fallito nell'effettuare una qualsiasi cura.}
{8}{}{Wow, ora so come come fargli del male!}
{9}{}{hai imparato la strenna Anatomia Vivente.}
{10}{}{Ricevi %1% punti esperienza per aver usato con successo dell'abilita' %2%.}
{11}{}{%1% curato di %2% HP.}
{12}{}{Dead. Too late to help this one. }
