{1}{}{Disabilities healed.}
{2}{}{Failed to heal disabilities.}
{3}{}{You can't do this in combat.}
{4}{}{You don't think there's any chance you could heal this.}
{5}{}{This critter is already healthy.}
{6}{}{You have already used this skill on this critter today.}
{7}{}{You fail to do any healing.}
{8}{}{Wow, now I really know how to hurt 'em!}
{9}{}{has earned Living Anatomy perk.}
{10}{}{You receive %1% experience for successful use of %2% skill.}
{11}{}{%1% healed for %2% HP.}
