{1}{}{Behinderungen geheilt.}
{2}{}{Behinderung konnte nicht geheilt werden.}
{3}{}{Im Kampf nicht möglich.}
{4}{}{Du glaubst nicht, dass es eine Möglichkeit gibt, das zu heilen.}
{5}{}{ is already healthy.}
{6}{}{%1% has already been healed with %2% skill today. Try tomorrow.}
{7}{}{Du konntest keine Heilung durchführen.}
{8}{}{Wow, jetzt weiß ich wirklich, wie ich sie verletzen kann!}
{9}{}{hat Lebende Anatomie Bonus verdient.}
{10}{}{Du erhältst %1% Erfahrung für den erfolgreichen Einsatz von %2% deiner Fertigkeit.}
{11}{}{%1% geheilt für %2% der TP.}
{12}{}{Dead. Too late to help this one. }
