#define SCRIPT_REALNAME "gl_g_trunk_space"
#include "headers/fo2tweaks/fo2tweaks.h"

#define set_trunk_space "trunk_space"

procedure bloat_trunk;

procedure map_enter_p_proc begin
  call bloat_trunk;
end

procedure start begin
  call bloat_trunk;
end

procedure bloat_trunk begin
  variable enabled := fo2tweaks_setting(sec_main, set_trunk_space);
  if enabled == 1 then begin
    set_proto_data(PID_CAR_TRUNK, PROTO_CN_MAX_SIZE, 99999);
    ndebug("trunk space set to 99999");
  end
end
