#define NAME "g_gl_level5"

#include "headers/fo2tweaks/fo2tweaks.h"

#define set_level5 "level5"

procedure map_enter_p_proc begin
  if map_first_run and cur_map_index == MAP_ARROYO_VILLAGE then begin
    variable enabled := fo2tweaks_setting(sec_main, set_level5);
    if enabled == 1 then begin
      give_exp_points(9500);
      ndebug("added 9500 XP");
      display_msg("You receive 9500 experience points, because you're a cheating little bastard");
    end
  end
end
