#include "headers/sfall/sfall.h"
#include "headers/sfall/dik.h"

procedure start;
procedure KeyPressHandler;

procedure KeyPressHandler begin
   variable
      event := get_sfall_arg,
      keyDX := get_sfall_arg,
      tmp;

   if key_pressed(DIK_V) then begin
      display_msg("Pressed V key: " + key_pressed(DIK_V));
   end
end

procedure start begin
   if game_loaded then begin
      register_hook_proc(HOOK_KEYPRESS, KeyPressHandler);
   end
end



// procedure start;
// procedure KeyPressHandler;


// procedure KeyPressHandler begin
//    variable
// 	 		who,
//       event := get_sfall_arg,
//       keyDX := get_sfall_arg;

//    if (keyDX == DIK_V) then begin
//       if event then begin
// 				// foreach who in party_member_list_critters begin
// 				// 	display_msg(obj_name(who) + " normal: thresh " + get_critter_stat(who, STAT_dmg_thresh) + ", res " + get_critter_stat(who, STAT_dmg_resist));
// 				// 	display_msg(obj_name(who) + " emp: thresh " + get_critter_stat(who, STAT_dmg_thresh_emp) + ", res " + get_critter_stat(who, STAT_dmg_resist_emp));
// 				// end
//          foreach who in party_member_list_critters begin
//          	display_msg(obj_name(who) + " stage: " + get_npc_level(obj_pid(who)));
//          end

//       end
//    end
// end

// procedure start begin
//    if game_loaded then begin
//       register_hook_proc(HOOK_KEYPRESS, KeyPressHandler);
//    end
// end
