{1}{}{Behinderungen geheilt.}
{2}{}{Behinderung konnte nicht geheilt werden.}
{3}{}{Im Kampf nicht möglich.}
{4}{}{Du glaubst nicht, dass es eine Möglichkeit gibt, das zu heilen.}
{5}{}{Diese Kreatur ist bereits gesund.}
{6}{}{Du hast diese Fertigkeit heute bereits bei diesem Lebewesen eingesetzt.}
{7}{}{Du konntest keine Heilung durchführen.}
{8}{}{Wow, jetzt weiß ich wirklich, wie ich sie verletzen kann!}
{9}{}{hat Lebende Anatomie Bonus verdient.}
{10}{}{Du erhältst %1% Erfahrung für den erfolgreichen Einsatz von %2% deiner Fertigkeit.}
{11}{}{%1% geheilt für %2% der TP.}
{12}{}{Tot. Zuspät, um hier zu helfen.}
