{1}{}{Behinderungen geheilt.}
{2}{}{Behinderung konnte nicht geheilt werden.}
{3}{}{Im Kampf nicht möglich.}
{4}{}{Du glaubst nicht, dass es eine Möglichkeit gibt, das zu heilen.}
{5}{}{Diese Kreatur ist bereits gesund.}
{6}{}{You have already used this skill on this critter today.}
{7}{}{You fail to do any healing.}
{8}{}{Wow, now I really know how to hurt 'em!}
{9}{}{has earned Living Anatomy perk.}
{10}{}{You receive %1% experience for successful use of %2% skill.}
{11}{}{%1% healed for %2% HP.}
{12}{}{Dead. Too late to help this one.}
